
= الحديث رقم ٧٥٧

[quote.hadith]
حَدَّثَنَا مُحَمَّدُ بْنُ بَشَّارٍ وَمُحَمَّدُ بْنُ يَحْيَى قَالاَ: حَدَّثَنَا أَبُو عَاصِمٍ أَنْبَأَنَا ابْنُ جُرَيْجٍ أَخْبَرَنِي عَبْدُ الْعَزِيزِ بْنُ عَبْدِ الْمَلِكِ بْنِ أَبِي مَحْذُورَةَ عَنْ عَبْدِ اللَّهِ بْنِ مُحَيْرِيزٍ- وَكَانَ يَتِيمًا فِي حِجْرِ أَبِي مَحْذُورَةَ بْنِ مِعْيَرٍ حِينَ جَهَّزَهُ إِلَى الشَّامِ- فَقُلْتُ لأَبِي مَحْذُورَةَ أَيْ عَمِّ إِنِّي خَارِجٌ إِلَى الشَّامِ وَإِنِّي أُسْأَلُ عَنْ تَأْذِينِكَ فَأَخْبَرَنِي أَنَّ أَبَا مَحْذُورَةَ قَالَ خَرَجْتُ فِي نَفَرٍ فَكُنَّا بِبَعْضِ الطَّرِيقِ فَأَذَّنَ مُؤَذِّنُ رَسُولِ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ بِالصَّلاَةِ عِنْدَ رَسُولِ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ فَسَمِعْنَا صَوْتَ الْمُؤَذِّنِ وَنَحْنُ عَنْهُ مُتَنَكِّبُونَ فَصَرَخْنَا نَحْكِيهِ نَهْزَأُ بِهِ فَسَمِعَ رَسُولُ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ فَأَرْسَلَ إِلَيْنَا قَوْمًا فَأَقْعَدُونَا بَيْنَ يَدَيْهِ فَقَالَ:. فَأَشَارَ إِلَيَّ الْقَوْمُ كُلُّهُمْ وَصَدَقُوا فَأَرْسَلَ كُلَّهُمْ وَحَبَسَنِي وَقَالَ لِي:. فَقُمْتُ وَلاَ شَيْءَ أَكْرَهُ إِلَيَّ مِنْ رَسُولِ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ وَلاَ مِمَّا يَأْمُرُنِي بِهِ فَقُمْتُ بَيْنَ يَدَيْ رَسُولِ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ فَأَلْقَى عَلَيَّ رَسُولُ اللَّهِ التَّأْذِينَ هُوَ بِنَفْسِهِ فَقَالَ:. ثُمَّ قَالَ لِي:. ثُمَّ دَعَانِي حِينَ قَضَيْتُ التَّأْذِينَ فَأَعْطَانِي صُرَّةً فِيهَا شَيْءٌ مِنْ فِضَّةٍ ثُمَّ وَضَعَ يَدَهُ عَلَى نَاصِيَةِ أَبِي مَحْذُورَةَ ثُمَّ أَمَرَّهَا عَلَى وَجْهِهِ مِنْ بَيْنِ يَدَيْهِ ثُمَّ عَلَى كَبِدِهِ ثُمَّ بَلَغَتْ يَدُ رَسُولِ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ سُرَّةَ أَبِي مَحْذُورَةَ ثُمَّ قَالَ رَسُولُ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ:. فَقُلْتُ يَا رَسُولَ اللَّهِ أَمَرْتَنِي بِالتَّأْذِينِ بِمَكَّةَ قَالَ:. فَذَهَبَ كُلُّ شَيْءٍ كَانَ لِرَسُولِ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ مِنْ كَرَاهِيَةٍ وَعَادَ ذَلِكَ كُلُّهُ مَحَبَّةً لِرَسُولِ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ فَقَدِمْتُ عَلَى عَتَّابِ بْنِ أَسِيدٍ عَامِلِ رَسُولِ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ بِمَكَّةَ فَأَذَّنْتُ مَعَهُ بِالصَّلاَةِ عَلَى أَمْرِ رَسُولِ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ. قَالَ وَأَخْبَرَنِي ذَلِكَ مَنْ أَدْرَكَ أَبَا مَحْذُورَةَ عَلَى مَا أَخْبَرَنِي عَبْدُ اللَّهِ بْنُ مُحَيْرِيزٍ.