
= الحديث رقم ٢٧٢٠

[quote.hadith]
حَدَّثَنَا أَبُو بَكْرِ بْنُ أَبِي شَيْبَةَ حَدَّثَنَا يَزِيدُ بْنُ هَارُونَ أَنْبَأَنَا هَمَّامُ بْنُ يَحْيَى عَنْ قَتَادَةَ عَنْ أَبِي الصِّدِّيقِ النَّاجِيِّ عَنْ أَبِي سَعِيدٍ الْخُدْرِيِّ قَالَ أَلاَ أُخْبِرُكُمْ بِمَا سَمِعْتُ مِنْ فِي رَسُولِ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ سَمِعَتْهُ أُذُنَايَ وَوَعَاهُ قَلْبِي:«إِنَّ عَبْدًا قَتَلَ تِسْعَةً وَتِسْعِينَ نَفْسًا ثُمَّ عَرَضَتْ لَهُ التَّوْبَةُ فَسَأَلَ عَنْ أَعْلَمِ أَهْلِ الأَرْضِ فَدُلَّ عَلَى رَجُلٍ فَأَتَاهُ. فَقَالَ إِنِّي قَتَلْتُ تِسْعَةً وَتِسْعِينَ نَفْسًا فَهَلْ لِي مِنْ تَوْبَةٍ قَالَ بَعْدَ تِسْعَةٍ وَتِسْعِينَ نَفْسًا. قَالَ فَانْتَضَى سَيْفَهُ فَقَتَلَهُ فَأَكْمَلَ بِهِ الْمِائَةَ ثُمَّ عَرَضَتْ لَهُ التَّوْبَةُ فَسَأَلَ عَنْ أَعْلَمِ أَهْلِ الأَرْضِ فَدُلَّ عَلَى رَجُلٍ فَأَتَاهُ فَقَالَ إِنِّي قَتَلْتُ مِائَةَ نَفْسٍ فَهَلْ لِي مِنْ تَوْبَةٍ قَالَ فَقَالَ وَيْحَكَ وَمَنْ يَحُولُ بَيْنَكَ وَبَيْنَ التَّوْبَةِ اخْرُجْ مِنَ الْقَرْيَةِ الْخَبِيثَةِ الَّتِي أَنْتَ فِيهَا إِلَى الْقَرْيَةِ الصَّالِحَةِ قَرْيَةِ كَذَا وَكَذَا فَاعْبُدْ رَبَّكَ فِيهَا. فَخَرَجَ يُرِيدُ الْقَرْيَةَ الصَّالِحَةَ فَعَرَضَ لَهُ أَجَلُهُ فِي الطَّرِيقِ فَاخْتَصَمَتْ فِيهِ مَلاَئِكَةُ الرَّحْمَةِ وَمَلاَئِكَةُ الْعَذَابِ قَالَ إِبْلِيسُ أَنَا أَوْلَى بِهِ إِنَّهُ لَمْ يَعْصِنِي سَاعَةً قَطُّ. قَالَ فَقَالَتْ مَلاَئِكَةُ الرَّحْمَةِ إِنَّهُ خَرَجَ تَائِبًا».