
= الحديث رقم ٤٢٦٦

[quote.hadith]
حَدَّثَنَا أَحْمَدُ بْنُ مُحَمَّدِ بْنِ يَحْيَى بْنِ سَعِيدٍ الْقَطَّانِ حَدَّثَنَا عَمْرُو بْنُ مُحَمَّدٍ الْعَنْقَزِيُّ حَدَّثَنَا أَسْبَاطُ بْنُ نَصْرٍ عَنِ السُّدِّيِّ عَنْ أَبِي سَعْدٍ الأَزْدِيِّ وَكَانَ قَارِئَ الأَزْدِ عَنْ أَبِي الْكَنُودِ عَنْ خَبَّابٍ فِي قَوْلِهِ تَعَالَى:إِلَى قَوْلِهِ:قَالَ جَاءَ الأَقْرَعُ بْنُ حَابِسٍ التَّمِيمِيُّ وَعُيَيْنَةُ بْنُ حِصْنٍ الْفَزَارِيُّ فَوَجَدُوا رَسُولَ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ مَعَ صُهَيْبٍ وَبِلاَلٍ وَعَمَّارٍ وَخَبَّابٍ قَاعِدًا فِي نَاسٍ مِنَ الضُّعَفَاءِ مِنَ الْمُؤْمِنِينَ فَلَمَّا رَأَوْهُمْ حَوْلَ النَّبِيِّ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ حَقَرُوهُمْ فَأَتَوْهُ فَخَلَوْا بِهِ وَقَالُوا إِنَّا نُرِيدُ أَنْ تَجْعَلَ لَنَا مِنْكَ مَجْلِسًا تَعْرِفُ لَنَا بِهِ الْعَرَبُ فَضْلَنَا فَإِنَّ وُفُودَ الْعَرَبِ تَأْتِيكَ فَنَسْتَحْيِي أَنْ تَرَانَا الْعَرَبُ مَعَ هَذِهِ الأَعْبُدِ فَإِذَا نَحْنُ جِئْنَاكَ فَأَقِمْهُمْ عَنْكَ فَإِذَا نَحْنُ فَرَغْنَا فَاقْعُدْ مَعَهُمْ إِنْ شِئْتَ. قَالَ:. قَالُوا فَاكْتُبْ لَنَا عَلَيْكَ كِتَابًا. قَالَ فَدَعَا بِصَحِيفَةٍ وَدَعَا عَلِيًّا لِيَكْتُبَ وَنَحْنُ قُعُودٌ فِي نَاحِيَةٍ فَنَزَلَ جِبْرَائِيلُ عَلَيْهِ السَّلاَمُ فَقَالَ:ثُمَّ ذَكَرَ الأَقْرَعَ بْنَ حَابِسٍ وَعُيَيْنَةَ بْنَ حِصْنٍ فَقَالَ:. ثُمَّ قَالَ:. قَالَ فَدَنَوْنَا مِنْهُ حَتَّى وَضَعْنَا رُكَبَنَا عَلَى رُكْبَتِهِ وَكَانَ رَسُولُ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ يَجْلِسُ مَعَنَا فَإِذَا أَرَادَ أَنْ يَقُومُ قَامَ وَتَرَكَنَا فَأَنْزَلَ اللَّهُ:وَلاَ تُجَالِسِ الأَشْرَافَ:- يَعْنِي عُيَيْنَةَ وَالأَقْرَعَ-- قَالَ هَلاَكًا- قَالَ أَمْرُ عُيَيْنَةَ وَالأَقْرَعِ. ثُمَّ ضَرَبَ لَهُمْ مَثَلَ الرَّجُلَيْنِ وَمَثَلَ الْحَيَاةِ الدُّنْيَا. قَالَ خَبَّابٌ فَكُنَّا نَقْعُدُ مَعَ النَّبِيِّ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ فَإِذَا بَلَغْنَا السَّاعَةَ الَّتِي يَقُومُ فِيهَا قُمْنَا وَتَرَكْنَاهُ حَتَّى يَقُومَ.