
= الحديث رقم ٣٩٣

[quote.hadith]
حَدَّثَنَا مُحَمَّدُ بْنُ بَشَّارٍ، حَدَّثَنَا عَبْدُ الأَعْلَى، وَأَبُو دَاوُدَ قَالاَ حَدَّثَنَا هِشَامٌ، عَنْ يَحْيَى بْنِ أَبِي كَثِيرٍ، عَنْ مُحَمَّدِ بْنِ إِبْرَاهِيمَ، أَنَّ أَبَا هُرَيْرَةَ، وَالسَّائِبَ الْقَارِئَ، كَانَا يَسْجُدَانِ سَجْدَتَىِ السَّهْوِ قَبْلَ التَّسْلِيمِ ‏.‏ قَالَ أَبُو عِيسَى حَدِيثُ ابْنِ بُحَيْنَةَ حَدِيثٌ حَسَنٌ صَحِيحٌ ‏.‏ وَالْعَمَلُ عَلَى هَذَا عِنْدَ بَعْضِ أَهْلِ الْعِلْمِ وَهُوَ قَوْلُ الشَّافِعِيِّ يَرَى سُجُودَ السَّهْوِ كُلِّهِ قَبْلَ السَّلاَمِ وَيَقُولُ هَذَا النَّاسِخُ لِغَيْرِهِ مِنَ الأَحَادِيثِ وَيَذْكُرُ أَنَّ آخِرَ فِعْلِ النَّبِيِّ صلى الله عليه وسلم كَانَ عَلَى هَذَا ‏.‏ وَقَالَ أَحْمَدُ وَإِسْحَاقُ إِذَا قَامَ الرَّجُلُ فِي الرَّكْعَتَيْنِ فَإِنَّهُ يَسْجُدُ سَجْدَتَىِ السَّهْوِ قَبْلَ السَّلاَمِ عَلَى حَدِيثِ ابْنِ بُحَيْنَةَ ‏.‏ وَعَبْدُ اللَّهِ ابْنُ بُحَيْنَةَ هُوَ عَبْدُ اللَّهِ بْنُ مَالِكٍ وَهُوَ ابْنُ بُحَيْنَةَ مَالِكٌ أَبُوهُ وَبُحَيْنَةُ أُمُّهُ ‏.‏ هَكَذَا أَخْبَرَنِي إِسْحَاقُ بْنُ مَنْصُورٍ عَنْ عَلِيِّ بْنِ عَبْدِ اللَّهِ بْنِ الْمَدِينِيِّ ‏.‏ قَالَ أَبُو عِيسَى وَاخْتَلَفَ أَهْلُ الْعِلْمِ فِي سَجْدَتَىِ السَّهْوِ مَتَى يَسْجُدُهُمَا الرَّجُلُ قَبْلَ السَّلاَمِ أَوْ بَعْدَهُ فَرَأَى بَعْضُهُمْ أَنْ يَسْجُدَهُمَا بَعْدَ السَّلاَمِ ‏.‏ وَهُوَ قَوْلُ سُفْيَانَ الثَّوْرِيِّ وَأَهْلِ الْكُوفَةِ ‏.‏ وَقَالَ بَعْضُهُمْ يَسْجُدُهُمَا قَبْلَ السَّلاَمِ ‏.‏ وَهُوَ قَوْلُ أَكْثَرِ الْفُقَهَاءِ مِنْ أَهْلِ الْمَدِينَةِ مِثْلِ يَحْيَى بْنِ سَعِيدٍ وَرَبِيعَةَ وَغَيْرِهِمَا وَبِهِ يَقُولُ الشَّافِعِيُّ ‏.‏ وَقَالَ بَعْضُهُمْ إِذَا كَانَتْ زِيَادَةً فِي الصَّلاَةِ فَبَعْدَ السَّلاَمِ وَإِذَا كَانَ نُقْصَانًا فَقَبْلَ السَّلاَمِ ‏.‏ وَهُوَ قَوْلُ مَالِكِ بْنِ أَنَسٍ ‏.‏ وَقَالَ أَحْمَدُ مَا رُوِيَ عَنِ النَّبِيِّ صلى الله عليه وسلم فِي سَجْدَتَىِ السَّهْوِ فَيُسْتَعْمَلُ كُلٌّ عَلَى جِهَتِهِ يَرَى إِذَا قَامَ فِي الرَّكْعَتَيْنِ عَلَى حَدِيثِ ابْنِ بُحَيْنَةَ فَإِنَّهُ يَسْجُدُهُمَا قَبْلَ السَّلاَمِ وَإِذَا صَلَّى الظُّهْرَ خَمْسًا فَإِنَّهُ يَسْجُدُهُمَا بَعْدَ السَّلاَمِ وَإِذَا سَلَّمَ فِي الرَّكْعَتَيْنِ مِنَ الظُّهْرِ وَالْعَصْرِ فَإِنَّهُ يَسْجُدُهُمَا بَعْدَ السَّلاَمِ وَكُلٌّ يُسْتَعْمَلُ عَلَى جِهَتِهِ ‏.‏ وَكُلُّ سَهْوٍ لَيْسَ فِيهِ عَنِ النَّبِيِّ صلى الله عليه وسلم ذِكْرٌ فَإِنَّ سَجْدَتَىِ السَّهْوِ قَبْلَ السَّلاَمِ ‏.‏ وَقَالَ إِسْحَاقُ نَحْوَ قَوْلِ أَحْمَدَ فِي هَذَا كُلِّهِ إِلاَّ أَنَّهُ قَالَ كُلُّ سَهْوٍ لَيْسَ فِيهِ عَنِ النَّبِيِّ صلى الله عليه وسلم ذِكْرٌ فَإِنْ كَانَتْ زِيَادَةً فِي الصَّلاَةِ يَسْجُدُهُمَا بَعْدَ السَّلاَمِ وَإِنْ كَانَ نُقْصَانًا يَسْجُدُهُمَا قَبْلَ السَّلاَمِ ‏.‏