
= الحديث رقم ٥٦٩

[quote.hadith]
قَالَ أَبُو عِيسَى قَالَ مُحَمَّدُ بْنُ بَشَّارٍ سَأَلْتُ يَحْيَى بْنَ سَعِيدٍ عَنْ هَذَا الْحَدِيثِ، فَحَدَّثَنِي عَنْ شُعْبَةَ، عَنْ عَبْدِ الرَّحْمَنِ بْنِ الْقَاسِمِ، عَنْ أَبِيهِ، عَنْ صَالِحِ بْنِ خَوَّاتٍ، عَنْ سَهْلِ بْنِ أَبِي حَثْمَةَ، عَنِ النَّبِيِّ صلى الله عليه وسلم بِمِثْلِ حَدِيثِ يَحْيَى بْنِ سَعِيدٍ الأَنْصَارِيِّ ‏.‏ وَقَالَ لِي يَحْيَى اكْتُبْهُ إِلَى جَنْبِهِ وَلَسْتُ أَحْفَظُ الْحَدِيثَ وَلَكِنَّهُ مِثْلُ حَدِيثِ يَحْيَى بْنِ سَعِيدٍ الأَنْصَارِيِّ ‏.‏ قَالَ أَبُو عِيسَى وَهَذَا حَدِيثٌ حَسَنٌ صَحِيحٌ ‏.‏ لَمْ يَرْفَعْهُ يَحْيَى بْنُ سَعِيدٍ الأَنْصَارِيُّ عَنِ الْقَاسِمِ بْنِ مُحَمَّدٍ وَهَكَذَا رَوَى أَصْحَابُ يَحْيَى بْنِ سَعِيدٍ الأَنْصَارِيِّ مَوْقُوفًا وَرَفَعَهُ شُعْبَةُ عَنْ عَبْدِ الرَّحْمَنِ بْنِ الْقَاسِمِ بْنِ مُحَمَّدٍ ‏.‏  570 - وَرَوَى مَالِكُ بْنُ أَنَسٍ، عَنْ يَزِيدَ بْنِ رُومَانَ، عَنْ صَالِحِ بْنِ خَوَّاتٍ، عَمَّنْ صَلَّى مَعَ النَّبِيِّ صلى الله عليه وسلم صَلاَةَ الْخَوْفِ فَذَكَرَ نَحْوَهُ ‏.‏ قَالَ أَبُو عِيسَى هَذَا حَدِيثٌ حَسَنٌ صَحِيحٌ ‏.‏ وَبِهِ يَقُولُ مَالِكٌ وَالشَّافِعِيُّ وَأَحْمَدُ وَإِسْحَاقُ ‏.‏ وَرُوِيَ عَنْ غَيْرِ وَاحِدٍ أَنَّ النَّبِيَّ صلى الله عليه وسلم صَلَّى بِإِحْدَى الطَّائِفَتَيْنِ رَكْعَةً رَكْعَةً فَكَانَتْ لِلنَّبِيِّ صلى الله عليه وسلم رَكْعَتَانِ وَلَهُمْ رَكْعَةٌ رَكْعَةٌ ‏.‏ قَالَ أَبُو عِيسَى أَبُو عَيَّاشٍ الزُّرَقِيُّ اسْمُهُ زَيْدُ بْنُ صَامِتٍ ‏.‏