
= الحديث رقم ٦٣١

[quote.hadith]
حَدَّثَنَا مُحَمَّدُ بْنُ يَحْيَى النَّيْسَابُورِيُّ، حَدَّثَنَا عَمْرُو بْنُ أَبِي سَلَمَةَ التِّنِّيسِيُّ، عَنْ صَدَقَةَ بْنِ عَبْدِ اللَّهِ، عَنْ مُوسَى بْنِ يَسَارٍ، عَنْ نَافِعٍ، عَنِ ابْنِ عُمَرَ، قَالَ قَالَ رَسُولُ اللَّهِ صلى الله عليه وسلم ‏"‏ فِي الْعَسَلِ فِي كُلِّ عَشَرَةِ أَزُقٍّ زِقٌّ ‏"‏ ‏.‏ وَفِي الْبَابِ عَنْ أَبِي هُرَيْرَةَ وَأَبِي سَيَّارَةَ الْمُتَعِيِّ وَعَبْدِ اللَّهِ بْنِ عَمْرٍو ‏.‏ قَالَ أَبُو عِيسَى حَدِيثُ ابْنِ عُمَرَ فِي إِسْنَادِهِ مَقَالٌ وَلاَ يَصِحُّ عَنِ النَّبِيِّ صلى الله عليه وسلم فِي هَذَا الْبَابِ كَبِيرُ شَيْءٍ وَالْعَمَلُ عَلَى هَذَا عِنْدَ أَكْثَرِ أَهْلِ الْعِلْمِ وَبِهِ يَقُولُ أَحْمَدُ وَإِسْحَاقُ ‏.‏ وَقَالَ بَعْضُ أَهْلِ الْعِلْمِ لَيْسَ فِي الْعَسَلِ شَيْءٌ ‏.‏ وَصَدَقَةُ بْنُ عَبْدِ اللَّهِ لَيْسَ بِحَافِظٍ وَقَدْ خُولِفَ صَدَقَةُ بْنُ عَبْدِ اللَّهِ فِي رِوَايَةِ هَذَا الْحَدِيثِ عَنْ نَافِعٍ ‏.‏ حَدَّثَنَا مُحَمَّدُ بْنُ بَشَّارٍ حَدَّثَنَا عَبْدُ الْوَهَّابِ الثَّقَفِيُّ حَدَّثَنَا عُبَيْدُ اللَّهِ بْنُ عُمَرَ عَنْ نَافِعٍ قَالَ سَأَلَنِي عُمَرُ بْنُ عَبْدِ الْعَزِيزِ عَنْ صَدَقَةِ الْعَسَلِ ‏.‏ قَالَ قُلْتُ مَا عِنْدَنَا عَسَلٌ نَتَصَدَّقُ مِنْهُ وَلَكِنْ أَخْبَرَنَا الْمُغِيرَةُ بْنُ حَكِيمٍ أَنَّهُ قَالَ لَيْسَ فِي الْعَسَلِ صَدَقَةٌ ‏.‏ فَقَالَ عُمَرُ عَدْلٌ مَرْضِيٌّ ‏.‏ فَكَتَبَ إِلَى النَّاسِ أَنْ تُوضَعَ ‏.‏ يَعْنِي عَنْهُمْ ‏.‏