
= الحديث رقم ١١٨٣

[quote.hadith]
وَقَالَتْ عَائِشَةُ أُنْزِلَ فِي الْقُرْآنِ عَشْرُ رَضَعَاتٍ مَعْلُومَاتٍ ‏.‏ فَنُسِخَ مِنْ ذَلِكَ خَمْسٌ وَصَارَ إِلَى خَمْسِ رَضَعَاتٍ مَعْلُومَاتٍ ‏.‏ فَتُوُفِّيَ رَسُولُ اللَّهِ صلى الله عليه وسلم وَالأَمْرُ عَلَى ذَلِكَ ‏.‏ حَدَّثَنَا بِذَلِكَ إِسْحَاقُ بْنُ مُوسَى الأَنْصَارِيُّ حَدَّثَنَا مَعْنٌ حَدَّثَنَا مَالِكٌ عَنْ عَبْدِ اللَّهِ بْنِ أَبِي بَكْرٍ عَنْ عَمْرَةَ عَنْ عَائِشَةَ بِهَذَا ‏.‏ وَبِهَذَا كَانَتْ عَائِشَةُ تُفْتِي وَبَعْضُ أَزْوَاجِ النَّبِيِّ صلى الله عليه وسلم وَهُوَ قَوْلُ الشَّافِعِيِّ وَإِسْحَاقَ ‏.‏ وَقَالَ أَحْمَدُ بِحَدِيثِ النَّبِيِّ صلى الله عليه وسلم ‏"‏ لاَ تُحَرِّمُ الْمَصَّةُ وَلاَ الْمَصَّتَانِ ‏"‏ ‏.‏ وَقَالَ إِنْ ذَهَبَ ذَاهِبٌ إِلَى قَوْلِ عَائِشَةَ فِي خَمْسِ رَضَعَاتٍ فَهُوَ مَذْهَبٌ قَوِيٌّ ‏.‏ وَجَبُنَ عَنْهُ أَنْ يَقُولَ فِيهِ شَيْئًا ‏.‏ وَقَالَ بَعْضُ أَهْلِ الْعِلْمِ مِنْ أَصْحَابِ النَّبِيِّ صلى الله عليه وسلم وَغَيْرِهِمْ يُحَرِّمُ قَلِيلُ الرَّضَاعِ وَكَثِيرُهُ إِذَا وَصَلَ إِلَى الْجَوْفِ ‏.‏ وَهُوَ قَوْلُ سُفْيَانَ الثَّوْرِيِّ وَمَالِكِ بْنِ أَنَسٍ وَالأَوْزَاعِيِّ وَعَبْدِ اللَّهِ بْنِ الْمُبَارَكِ وَوَكِيعٍ وَأَهْلِ الْكُوفَةِ ‏.‏ عَبْدُ اللَّهِ بْنُ أَبِي مُلَيْكَةَ هُوَ عَبْدُ اللَّهِ بْنُ عُبَيْدِ اللَّهِ بْنِ أَبِي مُلَيْكَةَ وَيُكْنَى أَبَا مُحَمَّدٍ وَكَانَ عَبْدُ اللَّهِ قَدِ اسْتَقْضَاهُ عَلَى الطَّائِفِ وَقَالَ ابْنُ جُرَيْجٍ عَنِ ابْنِ أَبِي مُلَيْكَةَ قَالَ أَدْرَكْتُ ثَلاَثِينَ مِنْ أَصْحَابِ النَّبِيِّ صلى الله عليه وسلم ‏.‏