
= الحديث رقم ١١٢٥

[quote.hadith]
حَدَّثَنَا ابْنُ أَبِي عُمَرَ، حَدَّثَنَا سُفْيَانُ بْنُ عُيَيْنَةَ، عَنِ ابْنِ جُرَيْجٍ، عَنْ سُلَيْمَانَ بْنِ مُوسَى، عَنِ الزُّهْرِيِّ، عَنْ عُرْوَةَ، عَنْ عَائِشَةَ، أَنَّ رَسُولَ اللَّهِ صلى الله عليه وسلم قَالَ ‏"‏ أَيُّمَا امْرَأَةٍ نُكِحَتْ بِغَيْرِ إِذْنِ وَلِيِّهَا فَنِكَاحُهَا بَاطِلٌ فَنِكَاحُهَا بَاطِلٌ فَنِكَاحُهَا بَاطِلٌ فَإِنْ دَخَلَ بِهَا فَلَهَا الْمَهْرُ بِمَا اسْتَحَلَّ مِنْ فَرْجِهَا فَإِنِ اشْتَجَرُوا فَالسُّلْطَانُ وَلِيُّ مَنْ لاَ وَلِيَّ لَهُ ‏"‏ ‏.‏ قَالَ أَبُو عِيسَى هَذَا حَدِيثٌ حَسَنٌ ‏.‏ وَقَدْ رَوَى يَحْيَى بْنُ سَعِيدٍ الأَنْصَارِيُّ وَيَحْيَى بْنُ أَيُّوبَ وَسُفْيَانُ الثَّوْرِيُّ وَغَيْرُ وَاحِدٍ مِنَ الْحُفَّاظِ عَنِ ابْنِ جُرَيْجٍ نَحْوَ هَذَا ‏.‏ قَالَ أَبُو عِيسَى وَحَدِيثُ أَبِي مُوسَى حَدِيثٌ فِيهِ اخْتِلاَفٌ رَوَاهُ إِسْرَائِيلُ وَشَرِيكُ بْنُ عَبْدِ اللَّهِ وَأَبُو عَوَانَةَ وَزُهَيْرُ بْنُ مُعَاوِيَةَ وَقَيْسُ بْنُ الرَّبِيعِ عَنْ أَبِي إِسْحَاقَ عَنْ أَبِي بُرْدَةَ عَنْ أَبِي مُوسَى عَنِ النَّبِيِّ صلى الله عليه وسلم ‏.‏ وَرَوَى أَسْبَاطُ بْنُ مُحَمَّدٍ وَزَيْدُ بْنُ حُبَابٍ عَنْ يُونُسَ بْنِ أَبِي إِسْحَاقَ عَنْ أَبِي إِسْحَاقَ عَنْ أَبِي بُرْدَةَ عَنْ أَبِي مُوسَى عَنِ النَّبِيِّ صلى الله عليه وسلم ‏.‏ وَرَوَى أَبُو عُبَيْدَةَ الْحَدَّادُ عَنْ يُونُسَ بْنِ أَبِي إِسْحَاقَ عَنْ أَبِي بُرْدَةَ عَنْ أَبِي مُوسَى عَنِ النَّبِيِّ صلى الله عليه وسلم نَحْوَهُ وَلَمْ يَذْكُرْ فِيهِ عَنْ أَبِي إِسْحَاقَ ‏.‏ وَقَدْ رُوِيَ عَنْ يُونُسَ بْنِ أَبِي إِسْحَاقَ عَنْ أَبِي بُرْدَةَ عَنِ النَّبِيِّ صلى الله عليه وسلم أَيْضًا ‏.‏ وَرَوَى شُعْبَةُ وَالثَّوْرِيُّ عَنْ أَبِي إِسْحَاقَ عَنْ أَبِي بُرْدَةَ عَنِ النَّبِيِّ صلى الله عليه وسلم ‏"‏ لاَ نِكَاحَ إِلاَّ بِوَلِيٍّ ‏"‏ ‏.‏ وَقَدْ ذَكَرَ بَعْضُ أَصْحَابِ سُفْيَانَ عَنْ سُفْيَانَ عَنْ أَبِي إِسْحَاقَ عَنْ أَبِي بُرْدَةَ عَنْ أَبِي مُوسَى ‏.‏ وَلاَ يَصِحُّ ‏.‏ وَرِوَايَةُ هَؤُلاَءِ الَّذِينَ رَوَوْا عَنْ أَبِي إِسْحَاقَ عَنْ أَبِي بُرْدَةَ عَنْ أَبِي مُوسَى عَنِ النَّبِيِّ صلى الله عليه وسلم ‏"‏ لاَ نِكَاحَ إِلاَّ بِوَلِيٍّ ‏"‏ ‏.‏ عِنْدِي أَصَحُّ لأَنَّ سَمَاعَهُمْ مِنْ أَبِي إِسْحَاقَ فِي أَوْقَاتٍ مُخْتَلِفَةٍ وَإِنْ كَانَ شُعْبَةُ وَالثَّوْرِيُّ أَحْفَظَ وَأَثْبَتَ مِنْ جَمِيعِ هَؤُلاَءِ الَّذِينَ رَوَوْا عَنْ أَبِي إِسْحَاقَ هَذَا الْحَدِيثَ فَإِنَّ رِوَايَةَ هَؤُلاَءِ عِنْدِي أَشْبَهُ لأَنَّ شُعْبَةَ وَالثَّوْرِيَّ سَمِعَا هَذَا الْحَدِيثَ مِنْ أَبِي إِسْحَاقَ فِي مَجْلِسٍ وَاحِدٍ ‏.‏