
= الحديث رقم ١١٨٢

[quote.hadith]
حَدَّثَنَا مُحَمَّدُ بْنُ عَبْدِ الأَعْلَى الصَّنْعَانِيُّ، قَالَ حَدَّثَنَا الْمُعْتَمِرُ بْنُ سُلَيْمَانَ، قَالَ سَمِعْتُ أَيُّوبَ، يُحَدِّثُ عَنْ عَبْدِ اللَّهِ بْنِ أَبِي مُلَيْكَةَ، عَنْ عَبْدِ اللَّهِ بْنِ الزُّبَيْرِ، عَنْ عَائِشَةَ، عَنِ النَّبِيِّ صلى الله عليه وسلم قَالَ ‏"‏ لاَ تُحَرِّمُ الْمَصَّةُ وَلاَ الْمَصَّتَانِ ‏"‏ ‏.‏ قَالَ وَفِي الْبَابِ عَنْ أُمِّ الْفَضْلِ وَأَبِي هُرَيْرَةَ وَالزُّبَيْرِ بْنِ الْعَوَّامِ وَابْنِ الزُّبَيْرِ ‏.‏ وَرَوَى غَيْرُ وَاحِدٍ هَذَا الْحَدِيثَ عَنْ هِشَامِ بْنِ عُرْوَةَ عَنْ أَبِيهِ عَنْ عَبْدِ اللَّهِ بْنِ الزُّبَيْرِ عَنِ النَّبِيِّ صلى الله عليه وسلم قَالَ ‏"‏ لاَ تُحَرِّمُ الْمَصَّةُ وَلاَ الْمَصَّتَانِ ‏"‏ ‏.‏ وَرَوَى مُحَمَّدُ بْنُ دِينَارٍ عَنْ هِشَامِ بْنِ عُرْوَةَ عَنْ أَبِيهِ عَنْ عَبْدِ اللَّهِ بْنِ الزُّبَيْرِ عَنِ الزُّبَيْرِ عَنِ النَّبِيِّ عَلَيْهِ الصَّلاَةُ وَالسَّلاَمُ ‏.‏ وَزَادَ فِيهِ مُحَمَّدُ بْنُ دِينَارٍ الْبَصْرِيُّ عَنِ الزُّبَيْرِ عَنِ النَّبِيِّ صلى الله عليه وسلم وَهُوَ غَيْرُ مَحْفُوظٍ ‏.‏ وَالصَّحِيحُ عِنْدَ أَهْلِ الْحَدِيثِ حَدِيثُ ابْنِ أَبِي مُلَيْكَةَ عَنْ عَبْدِ اللَّهِ بْنِ الزُّبَيْرِ عَنْ عَائِشَةَ عَنِ النَّبِيِّ صلى الله عليه وسلم ‏.‏ قَالَ أَبُو عِيسَى حَدِيثُ عَائِشَةَ حَدِيثٌ حَسَنٌ صَحِيحٌ ‏.‏ وَسَأَلْتُ مُحَمَّدًا عَنْ هَذَا فَقَالَ الصَّحِيحُ عَنِ ابْنِ الزُّبَيْرِ عَنْ عَائِشَةَ وَحَدِيثُ مُحَمَّدِ بْنِ دِينَارٍ خَطَأٌ أَخْطَأَ فِيهِ مُحَمَّدُ بْنُ دِينَارٍ وَزَادَ فِيهِ عَنِ الزُّبَيْرِ وَإِنَّمَا هُوَ هِشَامُ بْنُ عُرْوَةَ عَنْ أَبِيهِ عَنِ الزُّبَيْرِ ‏.‏ وَالْعَمَلُ عَلَى هَذَا عِنْدَ بَعْضِ أَهْلِ الْعِلْمِ مِنْ أَصْحَابِ النَّبِيِّ صلى الله عليه وسلم وَغَيْرِهِمْ ‏.‏