
= الحديث رقم ١١٢٦

[quote.hadith]
وَمِمَّا يَدُلُّ عَلَى ذَلِكَ مَا حَدَّثَنَا مَحْمُودُ بْنُ غَيْلاَنَ، قَالَ حَدَّثَنَا أَبُو دَاوُدَ، قَالَ أَنْبَأَنَا شُعْبَةُ، قَالَ سَمِعْتُ سُفْيَانَ الثَّوْرِيَّ، يَسْأَلُ أَبَا إِسْحَاقَ أَسَمِعْتَ أَبَا بُرْدَةَ يَقُولُ قَالَ رَسُولُ اللَّهِ صلى الله عليه وسلم ‏"‏ لاَ نِكَاحَ إِلاَّ بِوَلِيٍّ ‏"‏ ‏.‏ فَقَالَ نَعَمْ ‏.‏ فَدَلَّ هَذَا الْحَدِيثُ عَلَى أَنَّ سَمَاعَ شُعْبَةَ وَالثَّوْرِيِّ هَذَا الْحَدِيثَ فِي وَقْتٍ وَاحِدٍ ‏.‏ وَإِسْرَائِيلُ هُوَ ثِقَةٌ ثَبْتٌ فِي أَبِي إِسْحَاقَ ‏.‏ سَمِعْتُ مُحَمَّدَ بْنَ الْمُثَنَّى يَقُولُ سَمِعْتُ عَبْدَ الرَّحْمَنِ بْنَ مَهْدِيٍّ يَقُولُ مَا فَاتَنِي مِنْ حَدِيثِ الثَّوْرِيِّ عَنْ أَبِي إِسْحَاقَ الَّذِي فَاتَنِي إِلاَّ لَمَّا اتَّكَلْتُ بِهِ عَلَى إِسْرَائِيلَ لأَنَّهُ كَانَ يَأْتِي بِهِ أَتَمَّ ‏.‏ - وَحَدِيثُ عَائِشَةَ فِي هَذَا الْبَابِ عَنِ النَّبِيِّ صلى الله عليه وسلم ‏"‏ لاَ نِكَاحَ إِلاَّ بِوَلِيٍّ ‏"‏ حَدِيثٌ عِنْدِي حَسَنٌ ‏.‏ رَوَاهُ ابْنُ جُرَيْجٍ عَنْ سُلَيْمَانَ بْنِ مُوسَى عَنِ الزُّهْرِيِّ عَنْ عُرْوَةَ عَنْ عَائِشَةَ عَنِ النَّبِيِّ صلى الله عليه وسلم ‏.‏ وَرَوَاهُ الْحَجَّاجُ بْنُ أَرْطَاةَ وَجَعْفَرُ بْنُ رَبِيعَةَ عَنِ الزُّهْرِيِّ عَنْ عُرْوَةَ عَنْ عَائِشَةَ عَنِ النَّبِيِّ صلى الله عليه وسلم ‏.‏ وَرُوِيَ عَنْ هِشَامِ بْنِ عُرْوَةَ عَنْ أَبِيهِ عَنْ عَائِشَةَ عَنِ النَّبِيِّ صلى الله عليه وسلم مِثْلُهُ ‏.‏ وَقَدْ تَكَلَّمَ بَعْضُ أَصْحَابِ الْحَدِيثِ فِي حَدِيثِ الزُّهْرِيِّ عَنْ عُرْوَةَ عَنْ عَائِشَةَ عَنِ النَّبِيِّ صلى الله عليه وسلم ‏.‏ قَالَ ابْنُ جُرَيْجٍ ثُمَّ لَقِيتُ الزُّهْرِيَّ فَسَأَلْتُهُ فَأَنْكَرَهُ ‏.‏ فَضَعَّفُوا هَذَا الْحَدِيثَ مِنْ أَجْلِ هَذَا ‏.‏ وَذُكِرَ عَنْ يَحْيَى بْنِ مَعِينٍ أَنَّهُ قَالَ لَمْ يَذْكُرْ هَذَا الْحَرْفَ عَنِ ابْنِ جُرَيْجٍ إِلاَّ إِسْمَاعِيلُ بْنُ إِبْرَاهِيمَ ‏.‏ قَالَ يَحْيَى بْنُ مَعِينٍ وَسَمَاعُ إِسْمَاعِيلَ بْنِ إِبْرَاهِيمَ عَنِ ابْنِ جُرَيْجٍ لَيْسَ بِذَاكَ إِنَّمَا صَحَّحَ كُتُبَهُ عَلَى كُتُبِ عَبْدِ الْمَجِيدِ بْنِ عَبْدِ الْعَزِيزِ بْنِ أَبِي رَوَّادٍ مَا سَمِعَ مِنِ ابْنِ جُرَيْجٍ وَضَعَّفَ يَحْيَى رِوَايَةَ إِسْمَاعِيلَ بْنِ إِبْرَاهِيمَ عَنِ ابْنِ جُرَيْجٍ ‏.‏ - وَالْعَمَلُ فِي هَذَا الْبَابِ عَلَى حَدِيثِ النَّبِيِّ صلى الله عليه وسلم ‏"‏ لاَ نِكَاحَ إِلاَّ بِوَلِيٍّ ‏"‏ ‏.‏ عِنْدَ أَهْلِ الْعِلْمِ مِنْ أَصْحَابِ النَّبِيِّ صلى الله عليه وسلم مِنْهُمْ عُمَرُ بْنُ الْخَطَّابِ وَعَلِيُّ بْنُ أَبِي طَالِبٍ وَعَبْدُ اللَّهِ بْنُ عَبَّاسٍ وَأَبُو هُرَيْرَةَ وَغَيْرُهُمْ ‏.‏ وَهَكَذَا رُوِيَ عَنْ بَعْضِ فُقَهَاءِ التَّابِعِينَ أَنَّهُمْ قَالُوا لاَ نِكَاحَ إِلاَّ بِوَلِيٍّ ‏.‏ مِنْهُمْ سَعِيدُ بْنُ الْمُسَيَّبِ وَالْحَسَنُ الْبَصْرِيُّ وَشُرَيْحٌ وَإِبْرَاهِيمُ النَّخَعِيُّ وَعُمَرُ بْنُ عَبْدِ الْعَزِيزِ وَغَيْرُهُمْ وَبِهَذَا يَقُولُ سُفْيَانُ الثَّوْرِيُّ وَالأَوْزَاعِيُّ وَعَبْدُ اللَّهِ بْنُ الْمُبَارَكِ وَمَالِكٌ وَالشَّافِعِيُّ وَأَحْمَدُ وَإِسْحَاقُ ‏.‏