
= الحديث رقم ١٢١٦

[quote.hadith]
حَدَّثَنَا أَحْمَدُ بْنُ مَنِيعٍ، حَدَّثَنَا هُشَيْمٌ، أَنْبَأَنَا حُصَيْنٌ، وَإِسْمَاعِيلُ، وَمُجَالِدٌ، قَالَ هُشَيْمٌ وَحَدَّثَنَا دَاوُدُ، أَيْضًا عَنِ الشَّعْبِيِّ، قَالَ دَخَلْتُ عَلَى فَاطِمَةَ بِنْتِ قَيْسٍ فَسَأَلْتُهَا عَنْ قَضَاءِ، رَسُولِ اللَّهِ صلى الله عليه وسلم فِيهَا فَقَالَتْ طَلَّقَهَا زَوْجُهَا الْبَتَّةَ فَخَاصَمَتْهُ فِي السُّكْنَى وَالنَّفَقَةِ فَلَمْ يَجْعَلْ لَهَا النَّبِيُّ صلى الله عليه وسلم سُكْنَى وَلاَ نَفَقَةً ‏.‏ وَفِي حَدِيثِ دَاوُدَ قَالَتْ وَأَمَرَنِي أَنْ أَعْتَدَّ فِي بَيْتِ ابْنِ أُمِّ مَكْتُومٍ ‏.‏ قَالَ أَبُو عِيسَى هَذَا حَدِيثٌ حَسَنٌ صَحِيحٌ ‏.‏ وَهُوَ قَوْلُ بَعْضِ أَهْلِ الْعِلْمِ مِنْهُمُ الْحَسَنُ الْبَصْرِيُّ وَعَطَاءُ بْنُ أَبِي رَبَاحٍ وَالشَّعْبِيُّ وَبِهِ يَقُولُ أَحْمَدُ وَإِسْحَاقُ ‏.‏ وَقَالُوا لَيْسَ لِلْمُطَلَّقَةِ سُكْنَى وَلاَ نَفَقَةٌ إِذَا لَمْ يَمْلِكْ زَوْجُهَا الرَّجْعَةَ ‏.‏ وَقَالَ بَعْضُ أَهْلِ الْعِلْمِ مِنْ أَصْحَابِ النَّبِيِّ صلى الله عليه وسلم مِنْهُمْ عُمَرُ وَعَبْدُ اللَّهِ إِنَّ الْمُطَلَّقَةَ ثَلاَثًا لَهَا السُّكْنَى وَالنَّفَقَةُ ‏.‏ وَهُوَ قَوْلُ سُفْيَانَ الثَّوْرِيِّ وَأَهْلِ الْكُوفَةِ ‏.‏ وَقَالَ بَعْضُ أَهْلِ الْعِلْمِ لَهَا السُّكْنَى وَلاَ نَفَقَةَ لَهَا ‏.‏ وَهُوَ قَوْلُ مَالِكِ بْنِ أَنَسٍ وَاللَّيْثِ بْنِ سَعْدٍ وَالشَّافِعِيِّ ‏.‏ وَقَالَ الشَّافِعِيُّ إِنَّمَا جَعَلْنَا لَهَا السُّكْنَى بِكِتَابِ اللَّهِ قَالَ اللَّهُ تَعَالَى‏:‏ ‏65.1-1(‏لاَ تُخْرِجُوهُنَّ مِنْ بُيُوتِهِنَّ وَلاَ يَخْرُجْنَ إِلاَّ أَنْ يَأْتِينَ بِفَاحِشَةٍ مُبَيِّنَةٍ ‏)‏ قَالُوا هُوَ الْبَذَاءُ أَنْ تَبْذُوَ عَلَى أَهْلِهَا ‏.‏ وَاعْتَلَّ بِأَنَّ فَاطِمَةَ بِنْتَ قَيْسٍ لَمْ يَجْعَلْ لَهَا النَّبِيُّ صلى الله عليه وسلم السُّكْنَى لِمَا كَانَتْ تَبْذُو عَلَى أَهْلِهَا ‏.‏ قَالَ الشَّافِعِيُّ وَلاَ نَفَقَةَ لَهَا لِحَدِيثِ رَسُولِ اللَّهِ صلى الله عليه وسلم فِي قِصَّةِ حَدِيثِ فَاطِمَةَ بِنْتِ قَيْسٍ ‏.‏