
= الحديث رقم ١٤٢٩

[quote.hadith]
حَدَّثَنَا مُحَمَّدُ بْنُ بَشَّارٍ، حَدَّثَنَا أَبُو بَكْرٍ الْحَنَفِيُّ، أَخْبَرَنَا الضَّحَّاكُ بْنُ عُثْمَانَ، حَدَّثَنِي سَالِمٌ أَبُو النَّضْرِ، عَنْ بُسْرِ بْنِ سَعِيدٍ، عَنْ زَيْدِ بْنِ خَالِدٍ الْجُهَنِيِّ، أَنَّ رَسُولَ اللَّهِ صلى الله عليه وسلم سُئِلَ عَنِ اللُّقَطَةِ فَقَالَ ‏"‏ عَرِّفْهَا سَنَةً فَإِنِ اعْتُرِفَتْ فَأَدِّهَا وَإِلاَّ فَاعْرِفْ وِعَاءَهَا وَعِفَاصَهَا وَوِكَاءَهَا وَعَدَدَهَا ثُمَّ كُلْهَا فَإِذَا جَاءَ صَاحِبُهَا فَأَدِّهَا ‏"‏ ‏.‏ قَالَ أَبُو عِيسَى حَدِيثُ زَيْدِ بْنِ خَالِدٍ حَدِيثٌ حَسَنٌ صَحِيحٌ غَرِيبٌ مِنْ هَذَا الْوَجْهِ ‏.‏ قَالَ أَحْمَدُ أَصَحُّ شَيْءٍ فِي هَذَا الْبَابِ هَذَا الْحَدِيثُ ‏.‏ وَالْعَمَلُ عَلَى هَذَا عِنْدَ بَعْضِ أَهْلِ الْعِلْمِ مِنْ أَصْحَابِ النَّبِيِّ صلى الله عليه وسلم وَغَيْرِهِمْ وَرَخَّصُوا فِي اللُّقَطَةِ إِذَا عَرَّفَهَا سَنَةً فَلَمْ يَجِدْ مَنْ يَعْرِفُهَا أَنْ يَنْتَفِعَ بِهَا ‏.‏ وَهُوَ قَوْلُ الشَّافِعِيِّ وَأَحْمَدَ وَإِسْحَاقَ ‏.‏ وَقَالَ بَعْضُ أَهْلِ الْعِلْمِ مِنْ أَصْحَابِ النَّبِيِّ صلى الله عليه وسلم وَغَيْرِهِمْ يُعَرِّفُهَا سَنَةً فَإِنْ جَاءَ صَاحِبُهَا وَإِلاَّ تَصَدَّقَ بِهَا ‏.‏ وَهُوَ قَوْلُ سُفْيَانَ الثَّوْرِيِّ وَعَبْدِ اللَّهِ بْنِ الْمُبَارَكِ وَهُوَ قَوْلُ أَهْلِ الْكُوفَةِ لَمْ يَرَوْا لِصَاحِبِ اللُّقَطَةِ أَنْ يَنْتَفِعَ بِهَا إِذَا كَانَ غَنِيًّا ‏.‏ وَقَالَ الشَّافِعِيُّ يَنْتَفِعُ بِهَا وَإِنْ كَانَ غَنِيًّا لأَنَّ أُبَىَّ بْنَ كَعْبٍ أَصَابَ عَلَى عَهْدِ رَسُولِ اللَّهِ صلى الله عليه وسلم صُرَّةً فِيهَا مِائَةُ دِينَارٍ فَأَمَرَهُ رَسُولُ اللَّهِ صلى الله عليه وسلم أَنْ يُعَرِّفَهَا ثُمَّ يَنْتَفِعَ بِهَا وَكَانَ أُبَىٌّ كَثِيرَ الْمَالِ مِنْ مَيَاسِيرِ أَصْحَابِ رَسُولِ اللَّهِ صلى الله عليه وسلم فَأَمَرَهُ النَّبِيُّ صلى الله عليه وسلم أَنْ يُعَرِّفَهَا فَلَمْ يَجِدْ مَنْ يَعْرِفُهَا فَأَمَرَهُ النَّبِيُّ صلى الله عليه وسلم أَنْ يَأْكُلَهَا فَلَوْ كَانَتِ اللُّقَطَةُ لَمْ تَحِلَّ إِلاَّ لِمَنْ تَحِلُّ لَهُ الصَّدَقَةُ لَمْ تَحِلَّ لِعَلِيِّ بْنِ أَبِي طَالِبٍ لأَنَّ عَلِيَّ بْنَ أَبِي طَالِبٍ أَصَابَ دِينَارًا عَلَى عَهْدِ النَّبِيِّ صلى الله عليه وسلم فَعَرَّفَهُ فَلَمْ يَجِدْ مَنْ يَعْرِفُهُ فَأَمَرَهُ النَّبِيُّ صلى الله عليه وسلم بِأَكْلِهِ وَكَانَ لاَ يَحِلُّ لَهُ الصَّدَقَةُ ‏.‏ وَقَدْ رَخَّصَ بَعْضُ أَهْلِ الْعِلْمِ إِذَا كَانَتِ اللُّقَطَةُ يَسِيرَةً أَنْ يَنْتَفِعَ بِهَا وَلاَ يُعَرِّفَهَا ‏.‏ وَقَالَ بَعْضُهُمْ إِذَا كَانَ دُونَ دِينَارٍ يُعَرِّفُهَا قَدْرَ جُمُعَةٍ ‏.‏ وَهُوَ قَوْلُ إِسْحَاقَ بْنِ إِبْرَاهِيمَ ‏.‏