
= الحديث رقم ١٦٥٢

[quote.hadith]
حَدَّثَنِي مُحَمَّدُ بْنُ بَشَّارٍ، حَدَّثَنَا عَبْدُ الرَّحْمَنِ بْنُ مَهْدِيٍّ، حَدَّثَنَا سُفْيَانُ، عَنْ عَبْدِ الرَّحْمَنِ بْنِ الْحَارِثِ، عَنْ سُلَيْمَانَ بْنِ مُوسَى، عَنْ مَكْحُولٍ، عَنْ أَبِي سَلاَّمٍ، عَنْ أَبِي أُمَامَةَ، عَنْ عُبَادَةَ بْنِ الصَّامِتِ، أَنَّ النَّبِيَّ صلى الله عليه وسلم كَانَ يُنَفِّلُ فِي الْبَدْأَةِ الرُّبُعَ وَفِي الْقُفُولِ الثُّلُثَ ‏.‏ وَفِي الْبَابِ عَنْ سَعْدٍ وَابْنِ عَبَّاسٍ وَحَبِيبِ بْنِ مَسْلَمَةَ وَمَعْنِ بْنِ يَزِيدَ وَابْنِ عُمَرَ وَسَلَمَةَ بْنِ الأَكْوَعِ ‏.‏ وَحَدِيثُ عُبَادَةَ حَدِيثٌ حَسَنٌ ‏.‏ وَقَدْ رُوِيَ هَذَا الْحَدِيثُ عَنْ أَبِي سَلاَّمٍ عَنْ رَجُلٍ مِنْ أَصْحَابِ النَّبِيِّ صلى الله عليه وسلم عَنِ النَّبِيِّ صلى الله عليه وسلم ‏.‏ قَالَ الْبُخَارِيُّ لاَ يَصِّحُ حَدِيثُ سُلَيْمَانَ بْنِ مُوسَى إِنَّمَا رَوَاهُ دَاوُدُ بْنُ عَمْرٍو عَنْ أَبِي سَلاَّمٍ عَنِ النَّبِيِّ صلى الله عليه وسلم مُرْسَلاً وَسُلَيْمَانُ بْنُ مُوسَى مُنْكَرُ الْحَدِيثِ أَنَا لاَ أَرْوِي عَنْهُ شَيْئًا رَوَى أَحَادِيثَ مُنْكَرَةً عَامَّتُهَا مِنْهَا حَدِيثُ نَافِعٍ عَنِ ابْنِ عُمَرَ أَنَّ النَّبِيَّ صلى الله عليه وسلم كُفِّنَ فِي ثَلاَثَةِ أَثْوَابٍ ‏.‏ وَحَدِيثُهُ عَنْ نَافِعٍ عَنِ ابْنِ عُمَرَ ‏"‏ إِذَا طَلَعَ الْفَجْرُ فَقَدْ ذَهَبَ صَلاَةُ اللَّيْلِ وَالْوِتْرُ فَأَوْتِرُوا قَبْلَ الْفَجْرِ ‏"‏ ‏.‏ وَرَوَى عَنْ نَافِعٍ عَنِ ابْنِ عُمَرَ ‏"‏ أَفْشُوا السَّلاَمَ وَأَطْعِمُوا الطَّعَامَ وَكُونُوا إِخْوَانًا كَمَا أَمَرَكُمُ اللَّهُ ‏"‏ ‏.‏ وَحَدِيثُهُ ‏"‏ أَيُّمَا امْرَأَةٍ نَكَحَتْ بِغَيْرِ إِذْنِ وَلِيِّهَا كَانَ نِكَاحُهَا بَاطِلاً ‏"‏ ‏.‏ قَالَ أَبُو عِيسَى سُلَيْمَانُ بْنُ مُوسَى ثِقَةٌ عِنْدَ أَهْلِ الْحَدِيثِ لاَ نَعْلَمُ أَنَّ أَحَدًا ذَكَرَهُ بِسُوءٍ ‏.‏