
= الحديث رقم ١٧١٥

[quote.hadith]
حَدَّثَنَا مُحَمَّدُ بْنُ بَشَّارٍ، حَدَّثَنَا عَبْدُ الرَّحْمَنِ بْنُ مَهْدِيٍّ، عَنْ سُفْيَانَ، عَنْ عَلْقَمَةَ بْنِ مَرْثَدٍ، عَنْ سُلَيْمَانَ بْنِ بُرَيْدَةَ، عَنْ أَبِيهِ، قَالَ كَانَ رَسُولُ اللَّهِ صلى الله عليه وسلم إِذَا بَعَثَ أَمِيرًا عَلَى جَيْشٍ أَوْصَاهُ فِي خَاصَّةِ نَفْسِهِ بِتَقْوَى اللَّهِ وَمَنْ مَعَهُ مِنَ الْمُسْلِمِينَ خَيْرًا وَقَالَ ‏"‏ اغْزُوا بِسْمِ اللَّهِ وَفِي سَبِيلِ اللَّهِ قَاتِلُوا مَنْ كَفَرَ بِاللَّهِ وَلاَ تَغُلُّوا وَلاَ تَغْدِرُوا وَلاَ تُمَثِّلُوا وَلاَ تَقْتُلُوا وَلِيدًا فَإِذَا لَقِيتَ عَدُوَّكَ مِنَ الْمُشْرِكِينَ فَادْعُهُمْ إِلَى إِحْدَى ثَلاَثِ خِصَالٍ أَوْ خِلاَلٍ أَيَّتَهَا أَجَابُوكَ فَاقْبَلْ مِنْهُمْ وَكُفَّ عَنْهُمُ ادْعُهُمْ إِلَى الإِسْلاَمِ وَالتَّحَوُّلِ مِنْ دَارِهِمْ إِلَى دَارِ الْمُهَاجِرِينَ وَأَخْبِرْهُمْ إِنْ فَعَلُوا ذَلِكَ فَإِنَّ لَهُمْ مَا لِلْمُهَاجِرِينَ وَعَلَيْهِمْ مَا عَلَى الْمُهَاجِرِينَ وَإِنْ أَبَوْا أَنْ يَتَحَوَّلُوا فَأَخْبِرْهُمْ أَنَّهُمْ يَكُونُوا كَأَعْرَابِ الْمُسْلِمِينَ يَجْرِي عَلَيْهِمْ مَا يَجْرِي عَلَى الأَعْرَابِ لَيْسَ لَهُمْ فِي الْغَنِيمَةِ وَالْفَىْءِ شَيْءٌ إِلاَّ أَنْ يُجَاهِدُوا فَإِنْ أَبَوْا فَاسْتَعِنْ بِاللَّهِ عَلَيْهِمْ وَقَاتِلْهُمْ وَإِذَا حَاصَرْتَ حِصْنًا فَأَرَادُوكَ أَنْ تَجْعَلَ لَهُمْ ذِمَّةَ اللَّهِ وَذِمَّةَ نَبِيِّهِ فَلاَ تَجْعَلْ لَهُمْ ذِمَّةَ اللَّهِ وَلاَ ذِمَّةَ نَبِيِّهِ وَاجْعَلْ لَهُمْ ذِمَّتَكَ وَذِمَمَ أَصْحَابِكَ لأَنَّكُمْ إِنْ تُخْفِرُوا ذِمَّتَكُمْ وَذِمَمَ أَصْحَابِكُمْ خَيْرٌ مِنْ أَنْ تُخْفِرُوا ذِمَّةَ اللَّهِ وَذِمَّةَ رَسُولِهِ وَإِذَا حَاصَرْتَ أَهْلَ حِصْنٍ فَأَرَادُوكَ أَنْ تُنْزِلَهُمْ عَلَى حُكْمِ اللَّهِ فَلاَ تُنْزِلُوهُمْ وَلَكِنْ أَنْزِلْهُمْ عَلَى حُكْمِكَ فَإِنَّكَ لاَ تَدْرِي أَتُصِيبُ حُكْمَ اللَّهِ فِيهِمْ أَمْ لاَ ‏"‏ ‏.‏ أَوْ نَحْوَ هَذَا ‏.‏ قَالَ أَبُو عِيسَى وَفِي الْبَابِ عَنِ النُّعْمَانِ بْنِ مُقَرِّنٍ ‏.‏ وَحَدِيثُ بُرَيْدَةَ حَدِيثٌ حَسَنٌ صَحِيحٌ ‏.‏