
= الحديث رقم ١٨٣٢

[quote.hadith]
حَدَّثَنَا قُتَيْبَةُ، حَدَّثَنَا سُفْيَانُ بْنُ عُيَيْنَةَ، وَعَبْدُ الْعَزِيزِ بْنُ مُحَمَّدٍ، عَنْ زَيْدِ بْنِ أَسْلَمَ، عَنْ عَبْدِ الرَّحْمَنِ بْنِ وَعْلَةَ، عَنِ ابْنِ عَبَّاسٍ، قَالَ قَالَ رَسُولُ اللَّهِ صلى الله عليه وسلم ‏"‏ أَيُّمَا إِهَابٍ دُبِغَ فَقَدْ طَهُرَ ‏"‏ ‏.‏ هَذَا حَدِيثٌ حَسَنٌ صَحِيحٌ ‏.‏ وَالْعَمَلُ عَلَى هَذَا عِنْدَ أَكْثَرِ أَهْلِ الْعِلْمِ قَالُوا فِي جُلُودِ الْمَيْتَةِ إِذَا دُبِغَتْ فَقَدْ طَهُرَتْ ‏.‏ قَالَ أَبُو عِيسَى قَالَ الشَّافِعِيُّ أَيُّمَا إِهَابِ مَيْتَةٍ دُبِغَ فَقَدْ طَهُرَ إِلاَّ الْكَلْبَ وَالْخِنْزِيرَ ‏.‏ وَاحْتَجَّ بِهَذَا الْحَدِيثِ ‏.‏ وَقَالَ بَعْضُ أَهْلِ الْعِلْمِ مِنْ أَصْحَابِ النَّبِيِّ صلى الله عليه وسلم وَغَيْرِهِمْ إِنَّهُمْ كَرِهُوا جُلُودَ السِّبَاعِ وَإِنْ دُبِغَ وَهُوَ قَوْلُ عَبْدِ اللَّهِ بْنِ الْمُبَارَكِ وَأَحْمَدَ وَإِسْحَاقَ وَشَدَّدُوا فِي لُبْسِهَا وَالصَّلاَةِ فِيهَا ‏.‏ قَالَ إِسْحَاقُ بْنُ إِبْرَاهِيمَ إِنَّمَا مَعْنَى قَوْلِ رَسُولِ اللَّهِ صلى الله عليه وسلم ‏"‏ أَيُّمَا إِهَابٍ دُبِغَ فَقَدْ طَهُرَ ‏"‏ ‏.‏ جِلْدُ مَا يُؤْكَلُ لَحْمُهُ هَكَذَا فَسَّرَهُ النَّضْرُ بْنُ شُمَيْلٍ ‏.‏ وَقَالَ إِسْحَاقُ قَالَ النَّضْرُ بْنُ شُمَيْلٍ إِنَّمَا يُقَالُ الإِهَابُ لِجِلْدِ مَا يُؤْكَلُ لَحْمُهُ ‏.‏ قَالَ أَبُو عِيسَى وَفِي الْبَابِ عَنْ سَلَمَةَ بْنِ الْمُحَبِّقِ وَمَيْمُونَةَ وَعَائِشَةَ ‏.‏ وَحَدِيثُ ابْنِ عَبَّاسٍ حَسَنٌ صَحِيحٌ وَقَدْ رُوِيَ مِنْ غَيْرِ وَجْهٍ عَنِ ابْنِ عَبَّاسٍ عَنِ النَّبِيِّ صلى الله عليه وسلم نَحْوُ هَذَا ‏.‏ وَرُوِيَ عَنِ ابْنِ عَبَّاسٍ عَنْ مَيْمُونَةَ عَنِ النَّبِيِّ صلى الله عليه وسلم ‏.‏ وَرُوِيَ عَنْهُ عَنْ سَوْدَةَ وَسَمِعْتُ مُحَمَّدًا يُصَحِّحُ حَدِيثَ ابْنِ عَبَّاسٍ عَنِ النَّبِيِّ صلى الله عليه وسلم وَحَدِيثَ ابْنِ عَبَّاسٍ عَنْ مَيْمُونَةَ وَقَالَ احْتَمَلَ أَنْ يَكُونَ رَوَى ابْنُ عَبَّاسٍ عَنْ مَيْمُونَةَ عَنِ النَّبِيِّ صلى الله عليه وسلم وَرَوَى ابْنُ عَبَّاسٍ عَنِ النَّبِيِّ صلى الله عليه وسلم وَلَمْ يَذْكُرْ فِيهِ عَنْ مَيْمُونَةَ ‏.‏ قَالَ أَبُو عِيسَى وَالْعَمَلُ عَلَى هَذَا عِنْدَ أَكْثَرِ أَهْلِ الْعِلْمِ وَهُوَ قَوْلُ سُفْيَانَ الثَّوْرِيِّ وَابْنِ الْمُبَارَكِ وَالشَّافِعِيِّ وَأَحْمَدَ وَإِسْحَاقَ ‏.‏