
= الحديث رقم ٣١٥٦

[quote.hadith]
وَقَدْ رَوَى يَحْيَى بْنُ سَعِيدٍ الْقَطَّانُ، هَذَا الْحَدِيثَ عَنْ سُفْيَانَ، وَشُعْبَةَ، عَنْ عَلْقَمَةَ بْنِ مَرْثَدٍ، عَنْ سَعْدِ بْنِ عُبَيْدَةَ، عَنْ أَبِي عَبْدِ الرَّحْمَنِ، عَنْ عُثْمَانَ، عَنِ النَّبِيِّ صلى الله عليه وسلم حَدَّثَنَا بِذَلِكَ، مُحَمَّدُ بْنُ بَشَّارٍ حَدَّثَنَا يَحْيَى بْنُ سَعِيدٍ، عَنْ سُفْيَانَ، وَشُعْبَةَ، ‏.‏ قَالَ مُحَمَّدُ بْنُ بَشَّارٍ وَهَكَذَا ذَكَرَهُ يَحْيَى بْنُ سَعِيدٍ عَنْ سُفْيَانَ، وَشُعْبَةَ، غَيْرَ مَرَّةٍ عَنْ عَلْقَمَةَ بْنِ مَرْثَدٍ، عَنْ سَعْدِ بْنِ عُبَيْدَةَ، عَنْ أَبِي عَبْدِ الرَّحْمَنِ، عَنْ عُثْمَانَ، عَنِ النَّبِيِّ صلى الله عليه وسلم قَالَ مُحَمَّدُ بْنُ بَشَّارٍ وَأَصْحَابُ سُفْيَانَ لاَ يَذْكُرُونَ فِيهِ عَنْ سُفْيَانَ عَنْ سَعْدِ بْنِ عُبَيْدَةَ ‏.‏ قَالَ مُحَمَّدُ بْنُ بَشَّارٍ وَهُوَ أَصَحُّ ‏.‏ قَالَ أَبُو عِيسَى وَقَدْ زَادَ شُعْبَةُ فِي إِسْنَادِ هَذَا الْحَدِيثِ سَعْدَ بْنَ عُبَيْدَةَ وَكَأَنَّ حَدِيثَ سُفْيَانَ أَصَحُّ ‏.‏ قَالَ عَلِيُّ بْنُ عَبْدِ اللَّهِ قَالَ يَحْيَى بْنُ سَعِيدٍ مَا أَحَدٌ يَعْدِلُ عِنْدِي شُعْبَةَ وَإِذَا خَالَفَهُ سُفْيَانُ أَخَذْتُ بِقَوْلِ سُفْيَانَ ‏.‏ قَالَ أَبُو عِيسَى سَمِعْتُ أَبَا عَمَّارٍ يَذْكُرُ عَنْ وَكِيعٍ قَالَ قَالَ شُعْبَةُ سُفْيَانُ أَحْفَظُ مِنِّي وَمَا حَدَّثَنِي سُفْيَانُ عَنْ أَحَدٍ بِشَيْءٍ فَسَأَلْتُهُ إِلاَّ وَجَدْتُهُ كَمَا حَدَّثَنِي ‏.‏ وَفِي الْبَابِ عَنْ عَلِيٍّ وَسَعْدٍ ‏.‏