
= الحديث رقم ٣٢٠٩

[quote.hadith]
حَدَّثَنَا قُتَيْبَةُ، حَدَّثَنَا عَبْدُ الْعَزِيزِ بْنُ مُحَمَّدٍ، عَنِ الْعَلاَءِ بْنِ عَبْدِ الرَّحْمَنِ، عَنْ أَبِيهِ، عَنْ أَبِي هُرَيْرَةَ، أَنَّ رَسُولَ اللَّهِ صلى الله عليه وسلم قَالَ ‏"‏ مَنْ صَلَّى صَلاَةً لَمْ يَقْرَأْ فِيهَا بِأُمِّ الْقُرْآنِ فَهِيَ خِدَاجٌ فَهِيَ خِدَاجٌ غَيْرُ تَمَامٍ ‏"‏ ‏.‏ قَالَ قُلْتُ يَا أَبَا هُرَيْرَةَ إِنِّي أَحْيَانًا أَكُونُ وَرَاءَ الإِمَامِ ‏.‏ قَالَ يَا ابْنَ الْفَارِسِيِّ فَاقْرَأْهَا فِي نَفْسِكَ فَإِنِّي سَمِعْتُ رَسُولَ اللَّهِ صلى الله عليه وسلم يَقُولُ ‏"‏ قَالَ اللَّهُ تَعَالَى قَسَمْتُ الصَّلاَةَ بَيْنِي وَبَيْنَ عَبْدِي نِصْفَيْنِ فَنِصْفُهَا لِي وَنِصْفُهَا لِعَبْدِي وَلِعَبْدِي مَا سَأَلَ يَقُومُ الْعَبْدُ فَيَقْرَأُ ‏:‏ ‏1.2-2(‏الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ ‏)‏ فَيَقُولُ اللَّهُ حَمِدَنِي عَبْدِي فَيَقُولُ ‏:‏ ‏1.1-1(‏الرَّحْمَنِ الرَّحِيمِ ‏)‏ فَيَقُولُ اللَّهُ أَثْنَى عَلَىَّ عَبْدِي فَيَقُولُ ‏:‏ ‏1.4-4(‏ مَالِكِ يَوْمِ الدِّينِ ‏)‏ فَيَقُولُ مَجَّدَنِي عَبْدِي وَهَذَا لِي وَبَيْنِي وَبَيْنَ عَبْدِي ‏:‏ ‏1.5-5(‏إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ ‏)‏ وَآخِرُ السُّورَةِ لِعَبْدِي وَلِعَبْدِي مَا سَأَلَ يَقُولُ ‏:‏ ‏1.6-6(‏اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ * صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلاَ الضَّالِّينَ ‏)‏ ‏"‏ ‏.‏ قَالَ أَبُو عِيسَى هَذَا حَدِيثٌ حَسَنٌ ‏.‏ وَقَدْ رَوَى شُعْبَةُ وَإِسْمَاعِيلُ بْنُ جَعْفَرٍ وَغَيْرُ وَاحِدٍ عَنِ الْعَلاَءِ بْنِ عَبْدِ الرَّحْمَنِ عَنْ أَبِيهِ عَنْ أَبِي هُرَيْرَةَ عَنِ النَّبِيِّ صلى الله عليه وسلم نَحْوَ هَذَا الْحَدِيثِ ‏.‏ وَرَوَى ابْنُ جُرَيْجٍ وَمَالِكُ بْنُ أَنَسٍ عَنِ الْعَلاَءِ بْنِ عَبْدِ الرَّحْمَنِ عَنْ أَبِي السَّائِبِ مَوْلَى هِشَامِ بْنِ زُهْرَةَ عَنْ أَبِي هُرَيْرَةَ عَنِ النَّبِيِّ صلى الله عليه وسلم نَحْوَ هَذَا ‏.‏