
= الحديث رقم ٤٣٥٣

[quote.hadith]
حَدَّثَنَا أَبُو بَكْرٍ عَبْدُ الْقُدُّوسِ بْنُ مُحَمَّدٍ الْعَطَّارُ الْبَصْرِيُّ، حَدَّثَنَا عَلِيُّ بْنُ الْمَدِينِيِّ، قَالَ سَأَلْتُ يَحْيَى بْنَ سَعِيدٍ عَنْ مُحَمَّدِ بْنِ عَمْرِو بْنِ عَلْقَمَةَ، قَالَ تُرِيدُ الْعَفْوَ أَوْ تُشَدِّدُ فَقَالَ لاَ بَلْ أُشَدِّدُ ‏.‏ قَالَ لَيْسَ هُوَ مِمَّنْ تُرِيدُ كَانَ يَقُولُ أَشْيَاخُنَا أَبُو سَلَمَةَ وَيَحْيَى بْنُ عَبْدِ الرَّحْمَنِ بْنِ حَاطِبٍ ‏.‏ قَالَ يَحْيَى وَسَأَلْتُ مَالِكَ بْنَ أَنَسٍ عَنْ مُحَمَّدِ بْنِ عَمْرٍو فَقَالَ فِيهِ نَحْوَ مَا قُلْتُ ‏.‏ قَالَ عَلِيٌّ قَالَ يَحْيَى وَمُحَمَّدُ بْنُ عَمْرٍو أَعَلَى مِنْ سُهَيْلِ بْنِ أَبِي صَالِحٍ وَهُوَ عِنْدِي فَوْقَ عَبْدِ الرَّحْمَنِ بْنِ حَرْمَلَةَ ‏.‏ قَالَ عَلِيٌّ فَقُلْتُ لِيَحْيَى مَا رَأَيْتَ مِنْ عَبْدِ الرَّحْمَنِ بْنِ حَرْمَلَةَ قَالَ لَوْ شِئْتُ أَنْ أُلَقِّنَهُ لَفَعَلْتُ ‏.‏ قُلْتُ كَانَ يُلَقَّنُ قَالَ نَعَمْ ‏.‏ قَالَ عَلِيٌّ وَلَمْ يَرْوِ يَحْيَى عَنْ شَرِيكٍ وَلاَ عَنْ أَبِي بَكْرِ بْنِ عَيَّاشٍ وَلاَ عَنِ الرَّبِيعِ بْنِ صُبَيْحٍ وَلاَ عَنِ الْمُبَارَكِ بْنِ فَضَالَةَ ‏.‏ قَالَ أَبُو عِيسَى وَإِنْ كَانَ يَحْيَى بْنُ سَعِيدٍ الْقَطَّانُ قَدْ تَرَكَ الرِّوَايَةَ عَنْ هَؤُلاَءِ فَلَمْ يَتْرُكِ الرِّوَايَةَ عَنْهُمْ أَنَّهُ اتَّهَمَهُمْ بِالْكَذِبِ وَلَكِنَّهُ تَرَكَهُمْ لِحَالِ حِفْظِهِمْ ‏.‏ وَذُكِرَ عَنْ يَحْيَى بْنِ سَعِيدٍ أَنَّهُ كَانَ إِذَا رَأَى الرَّجُلَ يُحَدِّثُ عَنْ حِفْظِهِ مَرَّةً هَكَذَا وَمَرَّةً هَكَذَا لاَ يَثْبُتُ عَلَى رِوَايَةٍ وَاحِدَةٍ تَرَكَهُ ‏.‏ وَقَدْ حَدَّثَ عَنْ هَؤُلاَءِ الَّذِينَ تَرَكَهُمْ يَحْيَى بْنُ سَعِيدٍ الْقَطَّانُ عَبْدُ اللَّهِ بْنُ الْمُبَارَكِ وَوَكِيعُ بْنُ الْجَرَّاحِ وَعَبْدُ الرَّحْمَنِ بْنُ مَهْدِيٍّ وَغَيْرُهُمْ مِنَ الأَئِمَّةِ ‏.‏ قَالَ أَبُو عِيسَى وَهَكَذَا تَكَلَّمَ بَعْضُ أَهْلِ الْحَدِيثِ فِي سُهَيْلِ بْنِ أَبِي صَالِحٍ وَمُحَمَّدِ بْنِ إِسْحَاقَ وَحَمَّادِ بْنِ سَلَمَةَ وَمُحَمَّدِ بْنِ عَجْلاَنَ وَأَشْبَاهِ هَؤُلاَءِ مِنَ الأَئِمَّةِ إِنَّمَا تَكَلَّمُوا فِيهِمْ مِنْ قِبَلِ حِفْظِهِمْ فِي بَعْضِ مَا رَوَوْا وَقَدْ حَدَّثَ عَنْهُمُ الأَئِمَّةُ ‏.‏