
= الحديث رقم ١٠١

[quote.hadith]
حَدَّثَنِي بِشْرُ بْنُ الْحَكَمِ، قَالَ سَمِعْتُ يَحْيَى بْنَ سَعِيدٍ الْقَطَّانَ، ضَعَّفَ حَكِيمَ بْنَ جُبَيْرٍ وَعَبْدَ الأَعْلَى وَضَعَّفَ يَحْيَى مُوسَى بْنَ دِينَارٍ قَالَ حَدِيثُهُ رِيحٌ ‏.‏ وَضَعَّفَ مُوسَى بْنَ دِهْقَانَ وَعِيسَى بْنَ أَبِي عِيسَى الْمَدَنِيَّ ‏.‏ قَالَ وَسَمِعْتُ الْحَسَنَ بْنَ عِيسَى، يَقُولُ قَالَ لِيَ ابْنُ الْمُبَارَكِ إِذَا قَدِمْتَ عَلَى جَرِيرٍ فَاكْتُبْ عِلْمَهُ كُلَّهُ إِلاَّ حَدِيثَ ثَلاَثَةٍ لاَ تَكْتُبْ حَدِيثَ عُبَيْدَةَ بْنِ مُعَتِّبٍ وَالسَّرِيِّ بْنِ إِسْمَاعِيلَ وَمُحَمَّدِ بْنِ سَالِمٍ ‏.‏ قَالَ مُسْلِمٌ وَأَشْبَاهُ مَا ذَكَرْنَا مِنْ كَلاَمِ أَهْلِ الْعِلْمِ فِي مُتَّهَمِي رُوَاةِ الْحَدِيثِ وَإِخْبَارِهِمْ عَنْ مَعَايِبِهِمْ كَثِيرٌ يَطُولُ الْكِتَابُ بِذِكْرِهِ عَلَى اسْتِقْصَائِهِ وَفِيمَا ذَكَرْنَا كِفَايَةٌ لِمَنْ تَفَهَّمَ وَعَقَلَ مَذْهَبَ الْقَوْمِ فِيمَا قَالُوا مِنْ ذَلِكَ وَبَيَّنُوا وَإِنَّمَا أَلْزَمُوا أَنْفُسَهُمُ الْكَشْفَ عَنْ مَعَايِبِ رُوَاةِ الْحَدِيثِ وَنَاقِلِي الأَخْبَارِ وَأَفْتَوْا بِذَلِكَ حِينَ سُئِلُوا لِمَا فِيهِ مِنْ عَظِيمِ الْخَطَرِ إِذِ الأَخْبَارُ فِي أَمْرِ الدِّينِ إِنَّمَا تَأْتِي بِتَحْلِيلٍ أَوْ تَحْرِيمٍ أَوْ أَمْرٍ أَوْ نَهْىٍ أَوْ تَرْغِيبٍ أَوْ تَرْهِيبٍ فَإِذَا كَانَ الرَّاوِي لَهَا لَيْسَ بِمَعْدِنٍ لِلصِّدْقِ وَالأَمَانَةِ ثُمَّ أَقْدَمَ عَلَى الرِّوَايَةِ عَنْهُ مَنْ قَدْ عَرَفَهُ وَلَمْ يُبَيِّنْ مَا فِيهِ لِغَيْرِهِ مِمَّنْ جَهِلَ مَعْرِفَتَهُ كَانَ آثِمًا بِفِعْلِهِ ذَلِكَ غَاشًّا لِعَوَامِّ الْمُسْلِمِينَ إِذْ لاَ يُؤْمَنُ عَلَى بَعْضِ مَنْ سَمِعَ تِلْكَ الأَخْبَارَ أَنْ يَسْتَعْمِلَهَا أَوْ يَسْتَعْمِلَ بَعْضَهَا وَلَعَلَّهَا أَوْ أَكْثَرَهَا أَكَاذِيبُ لاَ أَصْلَ لَهَا مَعَ أَنَّ الأَخْبَارَ الصِّحَاحَ مِنْ رِوَايَةِ الثِّقَاتِ وَأَهْلِ الْقَنَاعَةِ أَكْثَرُ مِنْ أَنْ يُضْطَرَّ إِلَى نَقْلِ مَنْ لَيْسَ بِثِقَةٍ وَلاَ مَقْنَعٍ وَلاَ أَحْسِبُ كَثِيرًا مِمَّنْ يُعَرِّجُ مِنَ النَّاسِ عَلَى مَا وَصَفْنَا مِنْ هَذِهِ الأَحَادِيثِ الضِّعَافِ وَالأَسَانِيدِ الْمَجْهُولَةِ وَيَعْتَدُّ بِرِوَايَتِهَا بَعْدَ مَعْرِفَتِهِ بِمَا فِيهَا مِنَ التَّوَهُّنِ وَالضَّعْفِ إِلاَّ أَنَّ الَّذِي يَحْمِلُهُ عَلَى رِوَايَتِهَا وَالاِعْتِدَادِ بِهَا إِرَادَةُ التَّكَثُّرِ بِذَلِكَ عِنْدَ الْعَوَامِّ وَلأَنْ يُقَالَ مَا أَكْثَرَ مَا جَمَعَ فُلاَنٌ مِنَ الْحَدِيثِ وَأَلَّفَ مِنَ الْعَدَدِ ‏.‏ وَمَنْ ذَهَبَ فِي الْعِلْمِ هَذَا الْمَذْهَبَ وَسَلَكَ هَذَا الطَّرِيقَ فَلاَ نَصِيبَ لَهُ فِيهِ وَكَانَ بِأَنْ يُسَمَّى جَاهِلاً أَوْلَى مِنْ أَنْ يُنْسَبَ إِلَى عِلْمٍ ‏.‏